version: '3'

services:
  fivem:
    image: spritsail/fivem
    container_name: fivem
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - "/path/to/resources/folder:/config"
    ports:
      - "30120:30120"
      - "30120:30120/udp"
      - "40120:40120"
    environment:
      LICENSE_KEY: "cfxk_KmINVZ9APPLEeonuKTDR_YmmUA"
